stages:
  - test

test:
  stage: test
  image: python:3.10-slim
  script:
    - pip install hatch
    - hatch test --cover
  coverage: '/TOTAL.*? (100(?:\.0+)?\%\|[1-9]?\d(?:\.\d+)?\%)$/'
  tags:
    - docker
