stages:
  - build
  - test

test:
  stage: test
  image: python:3.10-slim
  before_script:
    - apt-get update
    - apt-get install -y git
  script:
    - pip install hatch
    - hatch test --cover
  coverage: '/TOTAL.*?(\d+\%)$/'
  tags:
    - docker

build-on-tag:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y git
  script:
    - echo "my-arithmetic-emariano deployment on stable servers"
    - pip install hatch hatch-vcs
    - hatch build -t wheel
    - hatch publish dist/*.whl
    - ls dist/
  rules:
    - if: '$CI_COMMIT_TAG'
  tags:
    - docker

build-on-develop:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y git
  script:
    - echo "my-arithmetic-emariano deployment on develop servers"
    - pip install hatch hatch-vcs
    - hatch build -t wheel
    - hatch publish dist/*.whl
    - ls dist/
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
  tags:
    - docker