name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.15

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          pip install hatch

      - name: Run tests with coverage
        run: hatch test --cover

  build:
    name: Build Project
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.15

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          pip install hatch hatch-vcs

      - name: Build wheel package
        run: hatch build -t wheel

      - name: List dist folder contents
        run: ls dist/

      - name: Deployment message
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "my-arithmetic-emariano deployment on stable servers"
          elif [[ "${{ github.ref }}" == refs/heads/develop ]]; then
            echo "my-arithmetic-emariano deployment on develop servers"
          fi
